import { JobListing, JobType, CandidateProfile, CompanyProfile, Tier, UserRole } from './types';

export const MOCK_CANDIDATE: CandidateProfile = {
  id: 'c1',
  name: 'Alex Rivera',
  role: 'Frontend Developer',
  bio: 'Passionate React developer looking for challenging projects. Experienced in building scalable web apps.',
  location: 'New York, NY',
  avatarUrl: 'https://picsum.photos/200/200?random=1',
  experience: 3,
  skills: [
    { name: 'React', level: 'Expert', verified: true },
    { name: 'TypeScript', level: 'Intermediate', verified: true },
    { name: 'Node.js', level: 'Intermediate', verified: false },
    { name: 'Tailwind CSS', level: 'Expert', verified: true },
  ],
  roadmap: null, // To be generated by AI
};

export const MOCK_COMPANY: CompanyProfile = {
  id: 'comp1',
  name: 'TechNova Solutions',
  industry: 'Software Development',
  location: 'San Francisco, CA',
  verified: true,
  logoUrl: 'https://picsum.photos/200/200?random=2',
  tier: Tier.PREMIUM,
  credits: {
    jobs: 15,
    inquiries: 500
  }
};

export const MOCK_JOBS: JobListing[] = [
  {
    id: 'j1',
    companyId: 'comp1',
    companyName: 'TechNova Solutions',
    companyLogo: 'https://picsum.photos/200/200?random=2',
    title: 'Senior React Engineer',
    type: JobType.FULL_TIME,
    location: 'Remote',
    salaryRange: '$120k - $150k',
    postedAt: '2 days ago',
    description: 'We are looking for a Senior React Engineer to lead our frontend team...',
    skills: ['React', 'Redux', 'TypeScript'],
    isFeatured: true,
    applicantsCount: 45
  },
  {
    id: 'j2',
    companyId: 'comp2',
    companyName: 'Urban Logistics',
    companyLogo: 'https://picsum.photos/200/200?random=3',
    title: 'Delivery Partner',
    type: JobType.GIG,
    location: 'Chicago, IL',
    salaryRange: '$25 / hr',
    postedAt: '5 hours ago',
    description: 'Instant payout daily gigs for reliable delivery partners.',
    skills: ['Driving', 'Navigation'],
    isFeatured: false,
    applicantsCount: 12
  },
  {
    id: 'j3',
    companyId: 'comp3',
    companyName: 'GovTech India',
    companyLogo: 'https://picsum.photos/200/200?random=4',
    title: 'Junior Data Analyst Notification',
    type: JobType.GOVT,
    location: 'New Delhi',
    salaryRange: 'Level 5 Pay Scale',
    postedAt: '1 week ago',
    description: 'Official notification for Junior Data Analyst recruitment drive 2024.',
    skills: ['SQL', 'Excel', 'Reasoning'],
    isFeatured: true,
    applicantsCount: 1200
  },
  {
    id: 'j4',
    companyId: 'comp4',
    companyName: 'Creative Studio',
    companyLogo: 'https://picsum.photos/200/200?random=5',
    title: 'Graphic Design Intern',
    type: JobType.INTERNSHIP,
    location: 'Hybrid',
    salaryRange: '$1500 Stipend',
    postedAt: '1 day ago',
    description: 'Learn from the best. 3 month internship with certificate.',
    skills: ['Photoshop', 'Illustrator'],
    isFeatured: false,
    applicantsCount: 89
  }
];
